---
abstract: 'SSL client certificate auth helper'
author:
  - 'Glen Hinkle <tempire@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-SslAuth
requires:
  IO::Socket::SSL: 1.39
  Mojolicious: 1.13
version: 0.03
