---
abstract: 'SSL client certificate auth helper'
author:
  - 'Glen Hinkle <tempire@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-SslAuth
requires:
  IO::Socket::SSL: 1.44
  Mojolicious: 2.81
resources:
  repository: git://github.com/tempire/mojolicious-plugin-sslauth.git
version: 0.07
